# 使用 Node 作为基础镜像
ARG NODE_VERSION=22-slim
FROM node:$NODE_VERSION


# ----- 基础配置 -----

# 设置生产环境标识
ENV NODE_ENV=production

# 安装常用的命令行工具
RUN apt-get update && apt-get install -y \
    vim \
    git \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

# 安装 GitHub CLI
RUN mkdir -p -m 755 /etc/apt/keyrings && \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | gpg --dearmor -o /etc/apt/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt-get update && \
    apt-get install -y gh && \
    rm -rf /var/lib/apt/lists/*


# ----- 安装 Supported Coding Agents -----

# 安装 npm 包形式的 agents
RUN npm install -g \
    @anthropic-ai/claude-code \
    @openai/codex \
    @github/copilot \
    @google/gemini-cli \
    @sourcegraph/amp \
     opencode-ai \
    @musistudio/claude-code-router ui \
    @qwen-code/qwen-code \
    && npm cache clean --force

# 安装 Cursor Agent CLI
RUN curl https://cursor.com/install -fsS | bash && \
    echo 'export PATH="$HOME/.local/bin:$PATH"' >> ~/.bashrc && \
    ln -sf "$HOME/.local/bin/cursor-agent" /usr/local/bin/cursor-agent

# 安装 Factory Droid
RUN curl -fsSL https://app.factory.ai/cli | sh


# ----- 健康检查 -----
HEALTHCHECK --interval=30s --timeout=3s --retries=3 --start-period=15s \
    CMD curl -f http://localhost:8080/ || exit 1


# ----- 启动服务 -----

# 设置工作目录
WORKDIR /projects

# 设置监听地址和端口
ENV HOST=0.0.0.0 PORT=8080

# 暴露端口
EXPOSE 8080

# 启动命令
CMD ["npx", "vibe-kanban"]
